theme= "onedark"

[editor]
line-number = "relative"
mouse = true
default-yank-register = '"'
color-modes = true
clipboard-provider = "termcode"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
