require('onedark').setup {
    style = 'darker',
    code_style = {
        comments = 'none',
        keywords = 'bold',
        functions = 'none',
        strings = 'none',
        variables = 'none'
    },
    diagnostics = {
       darker = true,
       undercurl = true, 
       background = false,
    },
    colors = {
    black =       "#000000",
    bg0 =         "#111111",
    bg1 =         "#2a2a2a",
    bg2 =         "#434343",
    bg3 =         "#525252",
    bg_d =        "#1b1b2b",
    bg_blue =     "#9191df",
    bg_yellow =   "#dfdf91",
    fg =          "#dcdcdc",
    purple =      "#bf8dff", --"#dd55dd",
    green =       "#73ce66", --"#55dd55",
    orange =      "#fd975a", --"#fd9744",
    blue =        "#78aaff", --"#6464fd",
    yellow =      "#ddd363", --"#eded44",
    cyan =        "#65c8d6", --"#55dddd",
    red =         "#ff6c6f",
    grey =        "#888888",
    light_grey =  "#bbbbbb",
    dark_cyan =   "#108a8a",
    dark_red =    "#8a2020",
    dark_yellow = "#abab34",
    dark_purple = "#8b348b",
    diff_add =    "#348b34",
    diff_delete = "#8b3434",
    diff_change = "#34348b",
    diff_text =   "#274964",
  },
}
require('onedark').load()
